update

diff --git a/scripts/configure b/scripts/configure
--- a/scripts/configure
+++ b/scripts/configure
@@ -1,6 +1,13 @@
 #!/usr/bin/env bash
 
 CONFIG_FILE=".env"
+
+if [ ! -f $CONFIG_FILE ]; then
+    echo "Error: Configuration file '$CONFIG_FILE' not found."
+    echo "Run 'scripts/configure' to configure your module."
+    exit 1
+fi
+
 source $CONFIG_FILE
 
 if [[ -z $MODEL_NAME ]]; then
@@ -9,7 +16,7 @@ if [[ -z $MODEL_NAME ]]; then
     MODEL_NAME=$MODEL_NAME
 else
     printf "\nEnter the name of the model your module will use:"
-    printf "\n(Current: $MODEL_NAME) ➡️ "
+    printf "\n(Current: $MODEL_NAME) ➜ "
     read -r NEW_MODEL_NAME
     MODEL_NAME=${NEW_MODEL_NAME:-$MODEL_NAME}
 fi
@@ -20,7 +27,7 @@ if [[ -z $MODEL_VERSION ]]; then
     MODEL_VERSION=$MODEL_VERSION
 else
     printf "\nEnter the version of the model your module will use:"
-    printf "\n(Current: $MODEL_VERSION) ➡️ "
+    printf "\n(Current: $MODEL_VERSION) ➜ "
     read -r NEW_MODEL_VERSION
     MODEL_VERSION=${NEW_MODEL_VERSION:-$MODEL_VERSION}
 fi
@@ -31,7 +38,7 @@ if [[ -z $DOCKER_HUB_USERNAME ]]; then
     DOCKER_HUB_USERNAME=$DOCKER_HUB_USERNAME
 else
     printf "\nEnter your Docker Hub username:"
-    printf "\n(Current: $DOCKER_HUB_USERNAME) ➡️ "
+    printf "\n(Current: $DOCKER_HUB_USERNAME) ➜ "
     read -r NEW_DOCKER_HUB_USERNAME
     DOCKER_HUB_USERNAME=${NEW_DOCKER_HUB_USERNAME:-$DOCKER_HUB_USERNAME}
 fi
@@ -39,29 +46,29 @@ fi
 if [[ -z $DOCKER_IMAGE ]]; then
     if [ -n "$MODEL_NAME" ] && [ -n "$MODEL_VERSION" ]; then
         printf "\nEnter the name of the Docker image:"
-        printf "\n(Default: $MODEL_NAME-$MODEL_VERSION) ➡️ "
+        printf "\n(Default: $MODEL_NAME-$MODEL_VERSION) ➜ "
         read -r DOCKER_IMAGE
         DOCKER_IMAGE=${DOCKER_IMAGE:-$MODEL_NAME-$MODEL_VERSION}
     else
-        printf "\nEnter the name of the Docker image:"
+        printf "\nEnter the name of the Docker image: "
         read -r DOCKER_IMAGE
         DOCKER_IMAGE=$DOCKER_IMAGE
     fi
 else
     printf "\nEnter the name of the Docker image:"
-    printf "\n(Current: $DOCKER_IMAGE) ➡️ "
+    printf "\n(Current: $DOCKER_IMAGE) ➜ "
     read -r NEW_DOCKER_IMAGE
     DOCKER_IMAGE=${NEW_DOCKER_IMAGE:-$DOCKER_IMAGE}
 fi
 
 if [[ -z $GITHUB_REPO ]]; then
     printf "\nEnter the GitHub repository URL for the module:"
-    printf "\n(Example: github.com/github_username/module_repo) ➡️ "
+    printf "\n(Example: github.com/github_username/module_repo) ➜ "
     read -r GITHUB_REPO
     GITHUB_REPO=$GITHUB_REPO
 else
     printf "\nEnter the GitHub repository URL for the module: "
-    printf "\n(Current: $GITHUB_REPO) ➡️ "
+    printf "\n(Current: $GITHUB_REPO) ➜ "
     read -r NEW_GITHUB_REPO
     GITHUB_REPO=${NEW_GITHUB_REPO:-$GITHUB_REPO}
 fi
diff --git a/scripts/run b/scripts/run
--- a/scripts/run
+++ b/scripts/run
@@ -1,39 +1,89 @@
 #!/usr/bin/env bash
 
-if [ $# -lt 1 ] || [ $# -gt 2 ]; then
-    echo "Usage: scripts/run [--local] <input>"
-    echo "Example: scripts/run 'What animal order do frogs belong to?'"
+CONFIG_FILE=".env"
+
+if [ ! -f $CONFIG_FILE ]; then
+    echo "Error: Configuration file '$CONFIG_FILE' not found."
+    echo "Run 'scripts/configure' to configure your module."
     exit 1
 fi
 
-if [ $1 == "--local" ] || [ $1 == "-l" ]; then
-    if [ $# -ne 2 ]; then
-        echo "❌ Error: Input is required."
-        echo "Example: scripts/run --local 'What animal order do frogs belong to?'"
-        exit 1
-    fi
-    echo "Running the Lilypad module Docker image locally..."
-    local=true
-    INPUT=$2
-else
-    INPUT=$1
+source $CONFIG_FILE
+
+if [ -z $MODEL_NAME ] || [ -z $MODEL_VERSION ]; then
+    echo "Error: Configure your module first:"
+    echo "scripts/configure"
+    echo ".env"
+    exit 1
 fi
 
-# Base64 encode the input
-JSON_INPUT="{"messages": [{"role": "user", "content": "$INPUT"}]}"
-BASE64_INPUT=$(echo $JSON_INPUT | base64)
-commit_hash=$(git log --pretty=format:%H | head -n 1)
+function request {
+    if ! printenv | grep -q "WEB3_PRIVATE_KEY=."; then
+        printf "Enter your wallet private key: "
+        read -r private_key
+        WEB3_PRIVATE_KEY=$private_key
+        echo "Private key set"
+        echo "(Hint: Use 'export WEB3_PRIVATE_KEY=<PRIVATE_KEY>' to avoid this prompt in the future)"
+    fi
+    echo "Copy the JSON below to form your request:"
+    echo '
+  "messages": [{
+    "role": "system",
+    "content": "you are a helpful AI assistant"
+  },
+  {
+    "role": "user",
+    "content": "what is the animal order of the frog?"
+  }],
+  "options": {
+    "temperature": 1.0
+  }
+'
+    printf "(Paste JSON as one line) ➔ "
+    read -r request
+    request="{\"model\": \"$MODEL_NAME:$MODEL_VERSION\", $request, \"stream\": false}"
+}
 
-if [ $local != true ]; then
+if [ $# -gt 2 ]; then
+    echo "Usage: scripts/run [--local] <request>"
+    echo "Example: scripts/run 'What animal order do frogs belong to?'"
+    exit 1
+elif [ $# -eq 0 ]; then
+    request
+else
+    while [[ $# -gt 0 ]]; do
+        case $1 in
+        --local | -l)
+            echo "Running the Lilypad module Docker image locally..."
+            local=true
+            shift
+            ;;
+        *)
+            request=$1
+            shift
+            ;;
+        esac
+    done
+
+    if [[ -z $request ]]; then
+        request
+    fi
+fi
+
+# Base64 encode the request
+base64_request=$(echo $request | base64 -w 0)
+
+if [ -z $local ]; then
+    commit_hash=$(git log --pretty=format:%H | head -n 1)
     MODULE=$GITHUB_REPO:$commit_hash
     echo "Running $MODULE on Lilypad Network..."
-    echo "Original input: $JSON_INPUT"
-    echo "Base64 encoded: $BASE64_INPUT"
-    lilypad run $MODULE -i prompt=$BASE64_INPUT
+    echo "Original request: $request"
+    echo "Base64 encoded: $base64_request"
+    lilypad run $MODULE -i request=$base64_request --web3-private-key=$WEB3_PRIVATE_KEY
 else
     MODULE=$DOCKER_IMAGE:$VERSION
     echo "Running $MODULE locally..."
-    echo "Original input: $JSON_INPUT"
-    echo "Base64 encoded: $BASE64_INPUT"
-    docker run $MODULE $BASE64_INPUT
+    echo "Original request: $request"
+    echo "Base64 encoded: $base64_request"
+    docker run $MODULE $base64_request
 fi
